apiVersion: v1
kind: Namespace
metadata:
  name: istio-explorations
  labels:
    istio-injection: enabled
---
apiVersion: v1
kind: Pod
metadata:
  name: routing-v1
  namespace: istio-explorations
  labels:
    app: routing-v1
spec:
  containers:
  - name: routing-v1
    image: docker.io/ratulb/routing:v1
---
apiVersion: v1
kind: Service
metadata:
  labels:
    app: routing-svc-v1
  name: routing-svc
  namespace: istio-explorations
spec:
  ports:
    - port: 8080
      protocol: TCP
      targetPort: 8080
  selector:
    app: routing-v1
---
apiVersion: networking.istio.io/v1alpha3
kind: Gateway
metadata:
  name: gateway-routing-v1
  namespace: istio-explorations
spec:
  selector:
    istio: ingressgateway # use istio default controller
  servers:
    - port:
        number: 80
        name: http
        protocol: HTTP
      hosts:
        - "*"
---
apiVersion: networking.istio.io/v1alpha3
kind: VirtualService
metadata:
  name: virtual-svc-rounting-v1
  namespace: istio-explorations
spec:
  hosts:
    - "*"
  gateways:
    - gateway-routing-v1
  http:
    - match:
        - uri:
            exact: /service1
        - uri:
            exact: /service2
        - uri:
            prefix: /
      route:
        - destination:
            host: routing-svc #Ref to cluster ip service above
            port:
              number: 8080
